dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
language: php
php:
  - 7.1
before_script:
  - mysql -u root -e 'create database test;'
  - cd tests
  - wget https://scrutinizer-ci.com/ocular.phar 
script: 
  - phpunit --bootstrap bootstrap.php --configuration phpunit.travis.xml --coverage-clover coverage.clover VhmisTest
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
