language: php
php:
  - 5.6
  - 5.5
  - 7.0
before_script:
  - composer self-update -n
  - cd tests
  - wget https://scrutinizer-ci.com/ocular.phar 
script: 
  - phpunit --bootstrap bootstrap.php --coverage-clover coverage.clover VhmisTest
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
